Pequenos ajustes finos
brunobatista25/generate_ruby_tests pull request #2
Opened 2018-09-13 17:32 UTC by reinaldorossetti

Regex foi reduzida pra somente uma.
Gemfile foi colocado a versão do Selenium, a versão adicionada está no link abaixo do siteprism, ele adiciona qual a versão que deve ser instalada do selenium webdriver.

https://github.com/natritmeyer/site_prism/blob/master/HISTORY.md

2018-09-14 18:10 UTC, brunobatista25 commented
da um git pull e adiciona no arquivo history.md as mudancas que vc fez. pra eu poder dar merge blz

2018-09-14 19:46 UTC, brunobatista25 requested changes
consertar o erro do gsub e colocar,
dar um pull para baixar a nova atualizacao e alterar o arquivo history e escrever as mudancas que vc fez

2018-09-14 19:46 UTC, brunobatista25 commented on lib/SkeletonWeb/features/support/hooks.rb
> +  scenario_name = scenario.gsub(/[^A-Za-z ]/, '').gsub(/\s+/, '_')
esse cara aqui tem que ter o nome exe:  ```scenario.name.gsub``` se não, isso ai não funciona

2018-09-15 02:51 UTC, reinaldorossetti commented
Rejeita o pull request, faltou o nome mesmo kkk vou dar o pull pra deixa no histórico.

2018-09-15 12:46 UTC, closed without merging